@startuml

RAM : do/Memories data
CPU : do/Computing data
Output : do/Display to User
ROM : do/Memories data for next times

[*] -> CPU 
CPU -down-> RAM : Send decoded data
RAM -left-> Output : Send to Output
RAM -down-> ROM : Memoring data
Output -left-> [*]
ROM ->[*]
@enduml